### ISSUE TITLE
migration to an new site

### ISSUE THREAD

**Issue by biZZa2** [georgringer/news#1171]
is there a way to export all news and import it on another typo3 install?

**Comment by dkoether** [comment]
Do you already have some news in your new TYPO3 installation and does the TYPO3 or EXT:news version change between the systems?

If versions stay the same and the new TYPO3 system has non existing news records you can easily export and import the news database tables.

**Comment by biZZa2** [comment]
thanks for your comment, yes its a completly new typo3 installation. I have installed the same news extension.  in the old system i made an export of my news folder to .t3d.

if i import the file on the new system, i became an error

> Oops, an error occurred!
No file found for given UID: 2060
[link](https://wiki.typo3.org/Exception/CMS/1317178604)
> 
 i don't understand how the images came to the new installation, should I transfer the files in advance?

is the error because i importetd earlier tt_news news?

**Comment by dkoether** [comment]
I can not suggest to use the import/export functionality with .t3d since there were some errors and misbehaviours in the past and I dont know the current state.

Lets split your problems in two parts:
First export your news database tables from the old TYPO3 system with tools like phpmyadmin, MySQL Workbench, Sequel Pro or the TYPO3 Extension "t3adminer" and import it to the new TYPO3 system in your desired way. The best way depends on your server environment and given tools.
Now you have all news records in your new TYPO3 system.

Lets fix your second problem:

> if i import the file on the new system, i became an error
> 
> > Oops, an error occurred!
> > No file found for given UID: 2060
> > [link](https://wiki.typo3.org/Exception/CMS/1317178604)
> 
> i don't understand how the images came to the new installation, should I transfer the files in advance?

This error occures when you have included a file to your news record but this file does not exist in your new TYPO3 fileadmin file storage. You have to copy the files into the new TYPO3 system. You can fix this error buy removing those files in the field "related_files" or "media" from the news record. 
This problem can have a different origin but lets first take a look on the most likely area.

> is the error because i importetd earlier tt_news news?

No, I dont think so.

**Comment by biZZa2** [comment]
thanks, the news are imported to new site. 
I export and import with phpmyadmin, I create in typo3 the folder with news-plugin and change per pypmyadmin the folder id like the old site. 
i copied the filadmin folder to new site, but the pictures are not taken over.

**Comment by peerlight** [comment]
I think you should have a look at table sys_file_references. And would also need sys_files and sys_file_metadata ...

**Comment by dkoether** [comment]
Hey @biZZa2, anything new about this? If you have already transferred your news to the new TYPO3 system successfully and you don't have anything more related to this, please close the issue.
