### ISSUE TITLE
10.1.44-MariaDB allow 191 max key length

### ISSUE THREAD

**Issue by prdt3e** [georgringer/news#1206]
Analyze Database Structure say:
remove index path_segment of tx_news_domain_model_news 
add KEY path_segment (path_segment(225), uid)

the problem:
the maximum key length is 191 

Solutions:
UPGRADE the mysql to 5.7.7(Mariadb 10.2.2) ?
Change the utf8mb column length to 191 (191*4=764) ?
Change the utf8mb to utf8 ?

**Comment by georgringer** [comment]
so which version are you using?

**Comment by prdt3e** [comment]
Sorry :)

Typo3: 10.3.0
News: 8.0.0-dev

**Comment by prdt3e** [comment]
As a workaround, I have edit the ext_tables.sql line 64 to:
KEY path_segment (path_segment (191), uid),

My server has allowed no more than 191.
But is a standard configuration with the latest Plesk.

**Comment by georgringer** [comment]
@froemken can you support me here?

**Comment by froemken** [comment]
He's right. I just have looked into the documentation for InnoDB tables where the key length in non-extended mode ist by default 767 Bytes. 767 bytes - 11 (for uid) / 4 (für MB4) = 189 Bytes maximum. I would prefer to use 185 just to be save with other configurations.
But why 191 works? InnoDB creates its own index for each table. If I remember correct it uses a row hash incl. the primary index. Maybe InnoDB does not incl. the space (11 bytes for uid), because this value is already in its internal index. But, as long as I'm not 100% sure about that I prefer to use a save length of 185.
