### ISSUE TITLE
RSS feed: broken inline images

### ISSUE THREAD

**Issue by Boa2** [georgringer/news#1294]
## Bug Report

**Current Behavior**
Images that are added via rte_ckeditor / rte_ckeditor_image are displayed in the detail via of the news, but are broken in the RSS feed.
In the detail view images are linked like so: "/fileadmin/..."
In the RSS feed the broken image links start like so: "https://example.comfileadmin/..."

**Expected behavior/output**
Images should be displayed.

**Environment**
- TYPO3 version(s): 9.5.15
- news version: 7.3.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Unix

**Possible Solution**

Thanks,
Andrea

**Comment by georgringer** [comment]
I don't use rte_ckeditor_image and also don't suggest using images in the rte. I don't know or plan to fix issues and not even sure if this is an issue of ext:news - therefore closing the issue

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Same problem here, but found a solution.

This is most likely due to a missing trailing slash in your constant `plugin.tx_sfeventmgt.rss.channel.link`:

```
plugin.tx_news.rss.channel {
	link = https://www.example.com
}
```

which is then used here:

`pageEventRSS.config.absRefPrefix = {$plugin.tx_sfeventmgt.rss.channel.link}`

Solutions:

Add a trailing slash to your domain or use "auto" like this:

`pageEventRSS.config.absRefPrefix = auto`

The correct domain is then taken from your site config, which is especially helpful with multidomain environments.
