### ISSUE TITLE
Search in Administration module works?

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#1311]
## Bug Report

Hi, can anyone confirm that search works in Administration module.

**Current Behavior**
Not working, whatever search - always show all news records.
(It worked on News 7.3.1)

**Environment**
- TYPO3 version(s): 9.5.19
- news version: Latest master
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Mint 19.3

Regards.

**Comment by JarvisH** [comment]
This issue relates to #1289 and was introduced in #1273

**Comment by zelcode** [comment]
With ending slash it works (#1289).

```php
$vars = GeneralUtility::_GET('route');
```
returns `'/module/web/NewsAdministration/'` - with ending slash -
so `function isInAdministrationModule()` will always be false.

**Comment by georgringer** [comment]
@liayn do you have time to look at that?

**Comment by liayn** [comment]
Yes

**Comment by liayn** [comment]
I tested this now on core 10.4.5 and latest master of news and the search works as expected.

**Comment by JarvisH** [comment]
Hi @liayn,

I think the problem occurs because the module path check needs to work with and without trailing slash for it to be compatible in Typo3 v9 and v10. It appears to me that in the pull request #1273, the argument order for the strpos check seem to be wrong:

Looks like this:
`return strpos('/module/web/NewsAdministration', $vars) !== false;`

Should be this:
`return strpos($vars, '/module/web/NewsAdministration') !== false;`

Or am I interpreting this wrong?

**Comment by liayn** [comment]
Yes, found that too. This checks works for v10, but not in v9 due to the param switch. PR is on its way.

**Comment by liayn** [comment]
@georgringer Ready to roll.
