### ISSUE TITLE
Can't edit/add new Catgories TYPO3 9.5.21 "No pseudo-site found in root line of page"

### ISSUE THREAD

**Issue by ShortSnow** [georgringer/news#1344]
Hello,

"The problem is the usage of the \TYPO3\CMS\Core\Compatibility\PseudoSiteTcaDisplayCondition::isInPseudoSite() for the slug fields introduced ext:news" 

more and detailed explanation: https://forge.typo3.org/issues/92331#change-431685

THX a lot

**Comment by martin-git-kristensen** [comment]
In news 8.4 change line 144 in Configuration/TCA/Overrides/sys_categori.php to 'displayCond' => 'VERSION:IS:false' will correct this error I think. In Configuration/TCA/tx_news_domain_model_news.php in the 'path_segment' section this change is allreade made.
Martin

**Comment by ShortSnow** [comment]
Thats the same solution as tt_adress use ist, i am not so deep in this function to confirm this. But if is the solution it must be changed here too: Configuration/TCA/tx_news_domain_model_tag.php

Arne

**Comment by mogensf** [comment]
I could only reproduce the issue, when there was no active page with same uid as the sys_category i wanted to edit.

The solution works fine. Thx Martin
(only tested for categories)

Because news extension is installed via composer in my setup, i needed a cleaner implementation.

In the provider extension of the project i added two files:

1. EXT:provider/Configuartion/TCA/Overrides/sys_category.php
```
<?php
defined('TYPO3_MODE') or die();

// https://github.com/georgringer/news/issues/1344
if($GLOBALS['TCA']['sys_category']['columns']['slug']['displayCond'] ==
    'USER:' . \TYPO3\CMS\Core\Compatibility\PseudoSiteTcaDisplayCondition::class . '->isInPseudoSite:pages:false')
{
    $GLOBALS['TCA']['sys_category']['columns']['slug']['displayCond'] = 'VERSION:IS:false';
}
```

2. EXT:provider/Configuartion/TCA/Overrides/tx_news_domain_model_tag.php
```
<?php
defined('TYPO3_MODE') or die();

// https://github.com/georgringer/news/issues/1344
if($GLOBALS['TCA']['tx_news_domain_model_tag']['columns']['slug']['displayCond'] ==
    'USER:' . \TYPO3\CMS\Core\Compatibility\PseudoSiteTcaDisplayCondition::class . '->isInPseudoSite:pages:false')
{
    $GLOBALS['TCA']['tx_news_domain_model_tag']['columns']['slug']['displayCond'] = 'VERSION:IS:false';
}
```


Make sure that the provider extension is loaded after the news extension.
This can be done by adding the news extension to the provider extension's dependencies.
Edit EXT:provider/ext_emconf.php
```
<?php
$EM_CONF[$_EXTKEY] = array(
    'title' => Provider Extension',
    'constraints' => [
        'depends' => [
            'news' => '8.4.0-8.4.99',
        ],
    ],
);
```

**Comment by martin-git-kristensen** [comment]
Hey Mogens

Thanks for your help – I have now made a small extension after your instructions and installed it via composer ☺

Med venlig hilsen

Martin Kristensen
Kommunikationstekniker
Indre Missions Hus
Korskærvej 25
7000 Fredericia
Tlf. 8227 1343
Mail: mkr@imh.dk<mailto:mkr@imh.dk>

Fra: mogensf [mailto:notifications@github.com]
Sendt: 24. september 2020 00:31
Til: georgringer/news <news@noreply.github.com>
Cc: Martin Kristensen <mkr@imh.dk>; Comment <comment@noreply.github.com>
Emne: Re: [georgringer/news] Can't edit/add new Catgories TYPO3 9.5.21 "No pseudo-site found in root line of page" (#1344)


I could only reproduce the issue, when there was no active page with same uid as the sys_category i wanted to edit.

The solution works fine. Thx Martin
(only tested for categories)

Because news extension is installed via composer in my setup, i needed a cleaner implementation.

In the provider extension of the project i added two files:

  1.  EXT:provider/Configuartion/TCA/Overrides/sys_category.php

<?php

defined('TYPO3_MODE') or die();



// https://github.com/georgringer/news/issues/1344

if($GLOBALS['TCA']['sys_category']['columns']['slug']['displayCond'] ==

    'USER:' . \TYPO3\CMS\Core\Compatibility\PseudoSiteTcaDisplayCondition::class . '->isInPseudoSite:pages:false')

{

    $GLOBALS['TCA']['sys_category']['columns']['slug']['displayCond'] = 'VERSION:IS:false';

}

  1.  EXT:provider/Configuartion/TCA/Overrides/tx_news_domain_model_tag.php

<?php

defined('TYPO3_MODE') or die();



// https://github.com/georgringer/news/issues/1344

if($GLOBALS['TCA']['tx_news_domain_model_tag']['columns']['slug']['displayCond'] ==

    'USER:' . \TYPO3\CMS\Core\Compatibility\PseudoSiteTcaDisplayCondition::class . '->isInPseudoSite:pages:false')

{

    $GLOBALS['TCA']['tx_news_domain_model_tag']['columns']['slug']['displayCond'] = 'VERSION:IS:false';

}

Make sure that the provider extension is loaded after the news extension.
This can be done by adding the news extension to the provider extension's dependencies.
Edit EXT:provider/ext_emconf.php

<?php

$EM_CONF[$_EXTKEY] = array(

    'title' => Provider Extension',

    'constraints' => [

        'depends' => [

            'news' => '8.4.0-8.4.99',

        ],

    ],

);

**Comment by georgringer** [comment]
changed it now
