### ISSUE TITLE
Extending News not working since version 8.4

### ISSUE THREAD

**Issue by matin73** [georgringer/news#1391]
Hello,

I extended News described here https://www.clickstorm.de/blog/extbase-objekte-ueberschreiben-erweitern/ and it worked with News 8.3 and TYPO3 10.4.x. Since version News 8.4 extending not working any more .... Where there any breaking changes?
Martin

**Comment by wimr0001** [comment]
Same problem for me.
Typo3_9.5.23 and news 8.5.0 works correctly with custom fields.
Typo3_10.4.11 and news 8.5.0, runs into an error.
#1580056272 TYPO3\CMS\Extbase\Persistence\Generic\Mapper\Exception\NonExistentPropertyException
The type of property GeorgRinger\News\Domain\Model\NewsDefault::eventStartdate could not be identified, as property eventStartdate is unknown to the TYPO3\CMS\Extbase\Reflection\ClassSchema instance of class GeorgRinger\News\Domain\Model\NewsDefault. Please make sure said property exists and that you cleared all caches to trigger a new build of said TYPO3\CMS\Extbase\Reflection\ClassSchema instance.

In the cache under /code/news, the customfields are added to tx_news_domain_model_news.
The customfields are also present in the cache onder data/extbase

**Comment by wimr0001** [comment]
Additional information: 
After clearing all caches the custom fields are added (information with <f:debug>{newsItem}) but not filled (null). After selecting the newsitem to go to the detailpage, the custom fields are not visible (with the error message given in the previous comment).

**Comment by wimr0001** [comment]
Additional information: 
After clearing all caches the custom fields are added (information with <f:debug>{newsItem}) but not filled (null). After selecting the newsitem to go to the detailpage, the custom fields are not visible (with the error message given in the previous comment).

**Comment by wimr0001** [comment]
I solved the problem.
Since I turned the website into a PWA, the backend was executed under a subdomain. Because the backend is not a PWA for me.
This subdomain contains only symbolic links to the main domain.
This worked under typo3 v9.
Under Typo3 V10, the caches are cleared, as I can see. But the problem mentioned above, exists.
The solution: Executing the backend in the subdomain (that is working also), clear the cache and the problem is solved.

**Comment by christophlehmann** [comment]
I think this may needs some hardening, but it's not that easy. Since updating from TYPO3 8.7 it occurs in our environment during deployments.

My simplified workflow is

* composer install
* create a new release dir
* transfer files to new release dir
* switch symlink to the new release dir
* clear opcache via web request 
* clear all caches via `./vendor/bin/typo3cms cache:flush` (this takes several seconds which seems normal, also locally in very small projects)

i currrently don't know at which state it breaks, but the first request arriving in the new release dir triggers `NonExistentPropertyException` and thus breaks all news plugins, also in upcoming requests. This could easily be reproduced with `hey -n 100000 -c 10 https://your-domain.com/` while doing a deployment.

My first thought was it's because of missing "extended classes" in `var/cache/code/news`, so i checked if helps when i run `./vendor/bin/typo3cms cache:flush` in the new release directory before switch the symlink in order to trigger their recreation. Sadly it doesn't help. My conclusion for this is that its maybe more a problem with the DataMapper and its cache. 

A small dive into the world of the Flow framework: It has AOP and also supports extending classes. It hardly prevents loading classes which are not properly build, means if its cache is empty one of the first steps is to build the "Proxy classes" (= EXT:news extended classes). 

I don't know yet if it helps if we "warmup" TYPO3 "extbase cache" (DataMapper cache) in `var/cache/data/extbase`, but it's not that easy to realize or more a heroic piece of work. One need to find every class which possibly could be extended.

What do you think about it? Can we reopen it?

**Comment by georgringer** [comment]
@christophlehmann wanna test that change https://github.com/georgringer/news/commit/296c43e31d09a03f845210b90700696c5cda8985 or discuss possible solutions via slack?

**Comment by rafu1987** [comment]
Hey there,

I don't know if it has to do with this specific issue here, but I'm getting the same error:

The type of property GeorgRinger\News\Domain\Model\NewsDefault::xxx could not be identified, as property xxx is unknown to the TYPO3\CMS\Extbase\Reflection\ClassSchema instance of class GeorgRinger\News\Domain\Model\NewsDefault. Please make sure said property exists and that you cleared all caches to trigger a new build of said TYPO3\CMS\Extbase\Reflection\ClassSchema instance.

I have a working site, let's say:
https://site1.dev

and adding a new site via symlink to the same folder, let's say:
https://site2.dev

Respecively the backend is accessed via https://site1.dev/typo3/ or https://site2.dev/typo3/

I'm getting the error above on site2, when i.e. only logged in the backend on site1, but not on site2. When logged in in both backends, I'm not getting any errors.

**Comment by georgringer** [comment]
just a question if you still got those issues with latest versions?

**Comment by matin73** [comment]
For me everything works fine. had some wrong configuration

**Comment by georgringer** [comment]
Thanks for your feedback
