### ISSUE TITLE
Empty category array on translated pages

### ISSUE THREAD

**Issue by Aero91** [georgringer/news#1414]
## Bug Report

**Current Behavior**
Debug output for {categories} in fluid template (Templates/Category/List.html) says that variable is empty.
Everything works just fine if the default language is selected, but if I view the translated page it says that there are no categories available at all. Plugin settings for default language and translatation are identical. Catgories are translated.

**Expected behavior/output**
Categories should be displayed for translated pages. 

**Environment**
- TYPO3 version(s): 10.4.10
- news version: 8.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Apache/2.4.46 (Fedora)

**Comment by georgringer** [comment]
Can you please share your relevant site config and screenshot of the plugin configuration + translated records because this works for me.

![image](https://user-images.githubusercontent.com/1905663/104026906-e73f6c80-51c6-11eb-9ed9-90ffed4d382a.png)

![image](https://user-images.githubusercontent.com/1905663/104026931-f1fa0180-51c6-11eb-858c-332599e8b9fd.png)

**Comment by georgringer** [comment]
can you test if it works with release from today (or change from #1404)

**Comment by Aero91** [comment]
> can you test if it works with release from today (or change from #1404)

Fixed in Version 8.5.1
Thanks!
