### ISSUE TITLE
lib.tx_news makes unneccessary queries

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/news#1579]
## Feature Request

**Is your feature request related to a problem? Please describe.**
lib.tx_news makes unneccessary queries about objects that are known already.  
The queries seem being required to provide rendering based on tt_content.

**Describe the solution you'd like**
I'd like a solution that is using known data to avoid the additional database-queries.

**Describe alternatives you've considered**
I've no solution yet.

**Teachability, Documentation, Adoption, Migration Strategy**
Older templates could optionally adjusted but would work without too (just without the small gain of speed and memory).  
The solution would require a change in tx_news itself and should be documented, so that older templates and TypoScript could be adjusted.

**Comment by DavidBruchmann** [comment]
@froemken maybe you have here an idea?

**Comment by froemken** [comment]
@DavidBruchmann I have just opened that issue here: #2490 
Regardless, if pagebrowser is activated or not, the listAction executes at least two COUNT queries. There is a clone of the used query (see `getQuery()`) that's why it is called twice. In one of our project we have 20 news plugin on one page which results into 3.800 queries. Most are for `tx_news_domain_model_news` and `pages` tables. Currently, I'm unsure, but maybe the paginator creates a lot of these queries. Without all these plugins we have ~300 queries. If I got the OK from customer I will investigate more time.

**Comment by DavidBruchmann** [comment]
I read that issue, therefore I got the idea you had a fix in mind here too perhaps :laughing:

**Comment by DavidBruchmann** [comment]
The issue is that in the templates content is created again by TypoScript sometimes, so it's not primarily related to the count issue.

This might be a good example, to show the issue, the data are known there already:  
https://github.com/georgringer/news/blob/9c74fd879a7ea61a3dda23d517646d31970ed484/Resources/Private/Templates/News/Detail.html#L97-L100

**Comment by DavidBruchmann** [comment]
so a fix could include one of these options, or perhaps another solution:

1. tell cObject `FLUIDTEMPLATE` (from lib.contentelement / tt_content) to render existing data instead of making a new query (how ?), would this be a core-challenge?
2. use an own (intermediate ?) DataProcessor
3. assign tt_content to the data (like 1 but assignment in viewhelper instead of TypoScript-Object, comparable with `renderObj = < tt_content` in `CONTENT`)

I haven't made any tests yet, but perhaps these ideas help a bit. Ideas might be still messed up, and need some more focussing.

**Comment by georgringer** [comment]
I am closing the issue as no progress done and really not easy to solve
