### ISSUE TITLE
Limit/ItemsPerPage Pagination Inconsistency

### ISSUE THREAD

**Issue by pulponair** [georgringer/news#1681]
## Bug Report

**Current Behavior**
Plugin in List mode, Limit Set to 3, Hidepagination set to 1, ItemsPerPage not set:
Plugin in Frontend lists 10 Records 

**Expected behavior/output**
Plugin should list 3 Records.

**Environment**
- TYPO3 version(s):11.5.4
- news version: 9.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Any

**Possible Solution**
Option 1:
Don't use the Paginator object if hidePagination is set to

Option 2:
If limit is less then the QueryResultPaginator default itemsPerPage (10) initialize it with "limit" as itemsPerPage

**Additional context**
Problem ist cause by the QueryResultPaginator::updatePaginatedItems called via updateInternalState on __construct.

Settings ItemsPerPage to limit within the plugin Flexform is not an option when you have hundreds of plugin instances.

**Comment by dahaupt** [comment]
@pulponair Hello, I have just encountered the same issue. I think this is related to [this core issue.](https://forge.typo3.org/issues/94965)

> Option 1:
Don't use the Paginator object if hidePagination is set to

According to the default [List Template](https://github.com/georgringer/news/blob/main/Resources/Private/Templates/News/List.html#L15-L20), this should already work like proposed, even if the paginator object is (unnecessarily) created.

> Option 2:
If limit is less than the QueryResultPaginator default itemsPerPage (10) initialize it with "limit" as itemsPerPage

This would only work in case the `limit` is below `itemsPerPage`, which makes the pagination superfluous anyway.  As `limit` is labeled with 'Max records displayed' it should also work if it is greater than `itemsPerPage`.

**Example situation:**
- 6 news records available
- `limit=4`
- `itemsPerPage=3`

**Current behavior**:
There are 3 records shown on the second page.

**Expected behavior**:
There is only 1 record shown on the second page.

**Comment by dahaupt** [comment]
@pulponair We could switch to the `ArrayPaginator` as mentioned in the core issue:

```
$paginator = new ArrayPaginator($newsRecords->toArray(), $currentPage, $itemsPerPage);
```

This would ensure the `limit` and `offset` of the original query result.

@georgringer Looking also forward to your feedback for this decision!

**Comment by pulponair** [comment]
> I think this is related to this core issue.
Yes it is ;(


> According to the default [List Template]
>(https://github.com/georgringer/news/blob/main/Resources/Private/Templates/News/List.html#L15-L20), this should already work >like proposed, even if the paginator object is (unnecessarily) created.
Yes, but creation refires the query with i"temsperpage" as limit (default 10). So the query result is wrong :(

**Comment by dahaupt** [comment]
@pulponair I am currently working on a core patch to solve this.

> Yes, but creation refires the query with i"temsperpage" as limit (default 10). So the query result is wrong :(

I could not reproduce that behavior in a recent test today. The original `QueryResult` object was never changed.

**Comment by pulponair** [comment]
@dahaupt it is i double checked that. It's done at updateInternalState within the constructor. Unfortunatly i can not look it it up right now. I ll provide you with details by tommorrow.

**Comment by dahaupt** [comment]
@pulponair Feel free to test my patch for the core: https://review.typo3.org/c/Packages/TYPO3.CMS/+/72817

**Comment by georgringer** [comment]
@pulponair can you test the PR? would help a lot
