### ISSUE TITLE
Can't add content elements to article any more after upgrade to TYPO3 11

### ISSUE THREAD

**Issue by artus70** [georgringer/news#1828]
## Bug Report

**Current Behavior**
When editing an article, trying to add a content element throws red error "Error undefined" and no new element is created. It worked in TYPO3 10 and stopped working in TYPO3 11 - both with news 9.4.0.

**Expected behavior/output**
A new empty content element should appear waiting to be filled.

**Environment**
- TYPO3 version(s): 11.5.13
- news version: 9.4.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10, macOS 12.4

**Additional context**
The error first appeared on an older article where some content elements already were added under TYPO3 10 (before upgrade to v11) and then a further content element should be added after the upgrade. Then confirmed problem under v11 with newly created article w/o existing content elements.

**Comment by sypets** [comment]
I could reproduce the problem. The problem seems to be related to gridelements (using latest early access master for v11). 

Created issue: https://github.com/CodersCare/gridelements_EA/issues/489

The issue is in private repo, since this is reproducable with the private early access version sorry.

I recommend to close here unless this can be reproduced with news without gridelements.
