### ISSUE TITLE
Allow setting of pluginNamespace in flexform

### ISSUE THREAD

**Issue by github1maxserv** [georgringer/news#1838]
## Feature Request

Two news lists with pagination on the same page control both paginators at the same time.

A setting in the flexform to change the pluginNamespace would make it possible to make both lists function independently. It's done in EXT:solr but it involves quite a few changes. A challenge will also be to adjust the routing configuration to reflect the pluginNamespace. Solr seems to have a service to handle that.

**Comment by georgringer** [comment]
As intermediate solution I suggest to render instead of e.g. 5 news 25 and do the pagination with JS. 

I don't plan to implement that feature myself because I don't really need it myself and haven't seen lots of requests for that - even though absolutly valid. This can for sure be added by a 3rd party extension - therefore I close this issue.

If anyone is interested in sponsoring this feature, please contact me in private via slack or mail.
