### ISSUE TITLE
Category and tag view show list when placed into a gridelements container

### ISSUE THREAD

**Issue by klodeckl** [georgringer/news#1887]
## Bug Report

If the news plug-in is inserted into a grid container column it always shows the list view when category or tag view is selected. If the plug-in is placed in a regular backend layout column without gridelements container it works as expected.

**Environment**
- TYPO3 version(s): 10
- news version: 10.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian buster

**Comment by georgringer** [comment]
can you test it with EXT:container. IMO it is an issue of gridelements

**Comment by klodeckl** [comment]
You’re right, it seems to be a gridelements issue. If I use gridelements with the “classic” typoscript template, it works correctly. But if I use gridelements withe the typoscript template with dataprocessing the described behaviour occurs. There ist also a problem when having a custom ce (with a dataprocessor) inside a gridelement.

**Comment by georgringer** [comment]
@Bunnyfield fyi ping

**Comment by klodeckl** [comment]
https://github.com/CodersCare/gridelements/issues/10

**Comment by Cybercraft-GmbH** [comment]
Just for the record: Usually this is an issue caused by FlexForm resolving of Gridelements. This will translate XML into arrays accessible by Fluid and by default this is activated, but it can be configured individually for containers and/or child elements.

https://docs.typo3.org/p/gridelementsteam/gridelements/main/en-us/Chapters/DataProcessing/Index.html
