### ISSUE TITLE
Nested Content Elements are rendered twice

### ISSUE THREAD

**Issue by itx-stefanie-doell** [georgringer/news#2018]
## Bug Report

**Current Behavior**
When I add nested content elements to news entries (container elements, with the help of the news_content_elements Extension) each content element is rendered twice.

**Possible Solution**
I changed the function getIdOfContentElements in the news model: 
if ($contentElement->getColPos() >= 0) {}
to
if ($contentElement->getColPos() == 0) { }
That solved the problem for me. I did not test this solution for other possible nested content examples, for example created via mask elements.

**Environment**
- TYPO3 version(s): 11.5.24
- news version: 10.0.3
- news-content-elements: 1.1.0
- PHP 8.0.11

**Comment by DavidBruchmann** [comment]
@itx-stefanie-doell  Do you think that it might be useful if that colPos could be configured?

**Comment by itx-stefanie-doell** [comment]
@DavidBruchmann I don't think so, but I'm not sure if my assumption is correct that the colPos is only > 0 if it is a child element of some other element...

**Comment by DavidBruchmann** [comment]
@itx-stefanie-doell ok, thanks for the response

**Comment by buepro** [comment]
Could you use [`skipRenderingChildContent`](https://github.com/b13/container#options-for-dataprocessing)?

**Comment by dkoether** [comment]
Hello @itx-stefanie-doell, hello @georgringer,

pointing to the documentation https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/Templates/RenderContentElements/Index.html#using-typoscript-with-nested-content-from-b13-container there is a way to render the container elements correctly by switching from EXT:news default `RECORDS` to `CONTENT`:

```
lib.tx_news.contentElementRendering = CONTENT
lib.tx_news.contentElementRendering {
    table = tt_content
    select {
        pidInList = 0
        uidInList.current = 1
        where = {#tx_container_parent}<1
        orderBy = sorting
        languageField = sys_language_uid
    }
}
```

Unfortunately this drags along some disadvantages: Among other things the order of translated records is mixed up.

While digging into this issue I think the value in `tx_news_related_news` needs to be set to `0` for content elements nested in container elements because they already have their relation to the news record by their container element in `tx_container_parent`. This value is set while saving new records and I wrote a save hook to take care of this content elements. A solution could look like this:

```
<?php

declare(strict_types=1);

namespace GeorgRinger\News\Hooks;

use TYPO3\CMS\Core\DataHandling\DataHandler;
use TYPO3\CMS\Core\SingletonInterface;

class NewsDataHandlerHooks implements SingletonInterface
{
    /**
     * After processing, only the changed/updated fields are available
     *
     * @param int|string $id An existing uid or "new..."
     * @param array<string, mixed> $fieldArray
     * @return void
     */
    public function processDatamap_postProcessFieldArray(
        string $status,
        string $table,
        int|string $id,
        array &$fieldArray,
        DataHandler $pObj
    ): void {
        if ($table === 'tt_content' && ((int)($fieldArray['tx_container_parent'] ?? false) > 0) && ((int)($fieldArray['tx_news_related_news'] ?? false) !== 0)) {
            $fieldArray['tx_news_related_news'] = '0';
        }
    }
}

```

What do you think about this topic, @georgringer? If you agree, I can provide a Pull Request :)

Best regards
Daniel

**Comment by georgringer** [comment]
still sounds like a lot of magic, isn't there an option to skip those during fetching - this would be then non destructive

**Comment by dkoether** [comment]
I found a problem when moving these content elements after creation inside/outside the container elements. They wont be shown afterwards. So the save hook approach is not working, I tried a different one:

I extended the TtContent and News model classes to change the method `getIdOfContentElements()`. I filter the elements by checking if they have a container parent:

```
protected function getIdOfContentElements($original = true): string
    {
        $idList = [];
        $contentElements = $this->getContentElements();
        if ($contentElements) {
            foreach ($this->getContentElements() as $contentElement) {
                if ($contentElement->getColPos() >= 0) {
                    if ($contentElement->getTxContainerParent() === 0) {
                        $idList[] = $original ? $contentElement->getUid() : $contentElement->_getProperty('_localizedUid');
                    }
                }
            }
        }
        return implode(',', $idList);
    }
``` 

This is also working for nesting container elements because the rendering of all placed elements is handled by themselves.

Even if I think it is cool if EXT:news is capable to render nested elements by EXT:container out-of-the-box, I`m not sure if you want to support it this way. What do you think? Should we instead update the documentation to give an example on how to extend the models?

**Comment by georgringer** [comment]
IMO it would be fine to have a dedicated method available which can be used, wanna do a PR?

**Comment by dkoether** [comment]
Yes, I will create a PR in the next days 👍🏻
