### ISSUE TITLE
Proposal - Set globalStoragePid instead of redirectToPageOnStart

### ISSUE THREAD

**Issue by isenegger-tim** [georgringer/news#400]
The variable redirectToPageOnStart improves the usability, but only in like 10% of the usecases, a user clicks directly on the news modul. Most of the time, the user is working on some pages, then clicks on the news modul - and can't find any news, because it selected the pid he's currently working on.

We could show the pagetree in the backend, yes, but wouldn't it be more elegant if the user is redirected automatically to a specified storagePid? Most of the time (in our cases) we only have one storage folder for news anyway.

My proposal is the following - add a field in the extension manager that's called something like "Set globalStoragePid". 

- If there is a pid defined, the module opens with this pid selected and hides the pagetree.
- If not, the pagetree is shown and the user can (like until now) select the storage himself. This usecase would be necessary, if there are more than just one storages in a project.

**Comment by DavidBruchmann** [comment]
Just mentioning that I had many projects where several news-plugins have been used, sometimes with the same, sometimes with different Storage-Folders.
I'm using the word 'plugin' here (like usually in TYPO3) for content-element for Frontend while "module" is used usually for Backend-modules (where news has also one). Therefore the word "module" for Frontend-Elements might be confusing sometimes.
"Set globalStoragePid" is not required as the storagePid can be set already globally by TypoScript anyway (and overridden in the pagetree if required).

**Comment by isenegger-tim** [comment]
@DavidBruchmann Thanks for your input.
Just for clarification - I am only talking about the backend module.

Anyway, how would you suggest to set the storagePid globally? I am more into frontend than backend, but trying to learn the latter as well.

**Comment by DavidBruchmann** [comment]
@isenegger-tim good for the clarification, then I misunderstood you as I thought you speak about the frontend-plugins.  
A definition by TypoScript like  
`plugin.tx_news.persistence.storagePid=23`  
should do the job.
If you host several domains in one TYPO3-installation you've to assure that this is defined hierarchical above the domain-related page-records to make it really global, but usually it's anyway desired to set it for each domain separated.

**Comment by christian-fries** [comment]
Setting `plugin.tx_news.persistence.storagePid = 18` seems not to be working in backend module (TYPO3 8.7.4, news 6.0.0), I still have to select the page where my news records are stored (also `module.tx_news.persistence.storagePid = 18` doesn't work).
As many of our projects need only one storage folder for news, it would be nice if it would be possible to define that pid for the backend module so that it always shows the records of this folder and hide the page tree.

It's currently possible to hide the page tree and define `tx_news.module.redirectToPageOnStart = 18` but this works only if the editor activates the news backend module straight after login. When he edits some page content first, a pid is set and therefore the user is not redirected and no news records are shown (if the selected pid is not the pid of the news storage folder which is most unlikely).

I think it would be a nice addition to have the possibility to set a storage pid in projects where only one storage folder is used, it would be much more comfortable for editors to use the backend module.

**Comment by DavidBruchmann** [comment]
Sorry, for backend you've to use
`tx_news.module.defaultPid.tx_news_domain_model_news = 123`

**Comment by christian-fries** [comment]
The `tx_news.module.defaultPid.tx_news_domain_model_news = 123` is only taken into account when creating new records while pid is 0. 

But I found the solution: There's a page TsConfig option called `allowedPage` ([docs](https://github.com/georgringer/news-documentation/blob/master/Documentation/AdministratorManual/Configuration/TsConfig/Index.rst#allowedpage)). When this page is set, the user is always redirected to the given page. Please note that this works only if pid is not 0 so that option should be best combined with `redirectToPageOnStart` for creating a continuous user experience.

**Comment by isenegger-tim** [comment]
The solution of @christian-fries works, thanks for helping guys.
