### ISSUE TITLE
URLs of localized news records in sitemap don't use uid of l10n_parent

### ISSUE THREAD

**Issue by peratoner-louis** [georgringer/news#683]
## Bug Report

**Current Behavior**

In the list view the URLs of a language version use the uid of the default language (`l10n_parent`) if it is a localized record.

In the news sitemap however, the URLs of a language version use the uid of the record in this language version even if a `l10n_parent` is available.

Therefore the URLs are different. With RealURL this leads to different URLs too:
`detail/news/a-news-item/`
`detail/news/a-news-item-1/`

**Expected behavior/output**

The URL in the sitemap should be the same as in list view -> it should use the uid of the default language, if available.

**Example**

Uid of the news record in the default language: 296
Uid of the localized news record: 297

In the list view, the urls of the localized records contain the uids of the default language:
`&tx_news_pi1[news]=296`

In the sitemap, the urls of the localized records contain their own uid:
`&tx_news_pi1[news]=297`

**Possible Solution**

```
diff --git a/typo3conf/ext/news/Classes/Hooks/TxNewsSitemapGenerator.php b/typo3conf/ext/news/Classes/Hooks/TxNewsSitemapGenerator.php
index f903b8d4..715d9044 100644
--- a/typo3conf/ext/news/Classes/Hooks/TxNewsSitemapGenerator.php
+++ b/typo3conf/ext/news/Classes/Hooks/TxNewsSitemapGenerator.php
@@ -182,8 +182,9 @@ class TxNewsSitemapGenerator extends AbstractSitemapGenerator
         }

         if ($link === '') {
             $newsType = (int)$newsRow['type'];
+            $newsId = $newsRow['l10n_parent'] ? $newsRow['l10n_parent'] : $newsRow['uid'];
             $conf = [
-                'additionalParams' => '&tx_news_pi1[news]=' . $newsRow['uid'] . $additionalParams,
+                'additionalParams' => '&tx_news_pi1[news]=' . $newsId . $additionalParams,
                 'forceAbsoluteUrl' => 1,
                 'parameter' => $forceSinglePid ?: $this->singlePid,
                 'returnLast' => 'url',
```

Tested with TYPO3 version 7.6.29 and news version 5.3.3 and 6.3.0 but there don't seem to be any relevant changes in newer versions.

- Composer Mode: no
- OS: Ubuntu 16.04

**Comment by IchHabRecht** [comment]
In my opinion the solution should be the other way around. The list view would need to use the localized uid instead of the parents uid.

Example:

- you have a hidden news in default language
- you have a visible translation of that (default) news
=> the translation is shown in the list view (which is correct as it isn't hidden and extbase queries include the translation for the list view)

- it isn't possible to see the detail view of the translated news due to the problem that the parent uid points to a hidden news

- if you would use the uid of the localized news instead, this news could be fetched from database and extbase would do correct language and workspace overlaying

**Comment by georgringer** [comment]
IMO this works now fine, closing the issue for now
