### ISSUE TITLE
Alternate Hreflang Tag

### ISSUE THREAD

**Issue by in-session** [georgringer/news#736]
Is there a way to check in which language the current news (in detail view) is available?
Otherwise an alternate hreflang tag would not be passed correctly if the news is not translated.

Example:

```
<f:for each="{newsItem.sys_language_uid}">
<v:page.header.link additionalAttributes="{hreflang: '**en (newsItem.sys_language_uid -> config.htmlTag_langKey)**'}" href="{f:uri.page(absolute: '1', noCacheHash: 1, additionalParams: {L: '** 0 (newsItem.sys_language_uid)**', tx_news_pi1: {controller: 'News',action: 'detail', news:newsItem.uid}})}" rel="alternate"></v:page.header.link>
</f:for>
```

**Comment by georgringer** [comment]
currently this is only possible by e.g. a custom VH

**Comment by georgringer** [comment]
with the language menu, you could use the hook `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['cms/tslib/class.tslib_menu.php']['filterMenuPages']`. I will try to dig into that for adding it by default - wanna sponsor that?

**Comment by ax-ha** [comment]
I am currently facing the same problem.
In my case this belongs to the page header hreflang fields as well as my language navigation.

Links are broken when there is a news entry in a non-default language without a translation.
(available is set to true but should be false, done by the LanguageMenuProcessor)

When there is a news entry in the default language without any translation, 
all links are generated with the news title of the default language like 
for e.g. /es-ES/wrong-message-title-from-default-language
(raising havoc because of double-content)

I do not have fallbacks defined for the most of the languages.

Is this a problem in my configuration, a bug (or maybe a compatibility problem) in 
LanguageMenuProcessor or a missing feature of the (by the way very awesome) news extension?

Anyhow the LanguageMenuProcessor seems to work in a correct way because the news detail page itself has a translation to all the given languages. 
Thanks for your help!

**Comment by georgringer** [comment]
This is a missing feature. no menu currently checks if the news record actually exists

**Comment by ax-ha** [comment]
Thank you Georg. 
So I will have to dig into much deeper and find the right place to solve that.
For now I am not sure if this is a future proof solution to add stuff like this to a site package.

**Comment by ax-ha** [comment]
My current solution:
I wrote a new component which loads NewsTranslations for the detected NewsId.  
(Only set on the news detail page)
Also a new ViewHelper component was required. This one is used during the language menu generation to detect if the language is contained in the NewsTranslations. 
Afterwards the setup typoscript and language menu generation had to be adjusted to work with the new stuff as well.

**Comment by georgringer** [comment]
this is implemented since some versions
