### ISSUE TITLE
Crop value from FileReference (for News image) is ignored

### ISSUE THREAD

**Issue by mrk131324** [georgringer/news#75]
In fact the crop value is not accessible in the FE at all, because the old  

\TYPO3\CMS\Extbase\Domain\Model\FileReference

does not implement it.

**Comment by georgringer** [comment]
I can not reproduce that the default templates, using latest news and core

**Comment by xperseguers** [comment]
That's really interesting, I wonder how this can work for you because indeed, I don't see the `crop` information available in Frontend in TYPO3 v8. To make it work, I had to do following:

in `EXT:extbase/Classes/Domain/Model/FileReference.php`, add a field and a getter:

```
/**
 * @string
 */
protected $crop;

public function getCrop() : string
{
    return $this->crop;
}
```

In `EXT:news/Resources/Private/Partials/Detail/FalMediaImage.html` (or an override), modify the `<f:image ` tags to read `<f:image crop="{mediaElement.crop}" ...`

**Comment by xperseguers** [comment]
Looks like you're at version 7.x whereas my local version is 5.3. You now extend another base class for class `FileReference` and problem is possibly gone. Will have to test again but will have to do extensive tests first because upgrading to new major version is not something I do "quickly".

**Comment by xperseguers** [comment]
https://review.typo3.org/#/c/58673/

**Comment by georgringer** [comment]
I will close that in the meantime. feel free to reopen later

**Comment by rupasix** [comment]
Hey. I use T3 9.5.5, news 7.2.0 and still i can't access crop property in Fluid template. I think this issue should be reopened.

**Comment by georgringer** [comment]
the crop information is available with e.g. `{newsItem.mediaPreviews.0.originalResource.properties.crop}`  but there is no need to access that as you can just use `<f:media class="img-fluid" cropVariant="specialMobile" file="{newsItem.mediaPreviews.0}"  />`
