### ISSUE TITLE
Speaking URL path segment eval

### ISSUE THREAD

**Issue by zelcode** [georgringer/news#754]
## Bug Report

**Current Behavior**
When you have 2 records with same title the `path_segment` is identical.

First title: AAA
path_segment: `aaa`

Second title: AAA
path_segment: `aaa`

**Expected behavior/output**
Next identical title should have next number appended.

First title: BBB
path_segment: `bbb`

Second title: BBB
path_segment: `bbb-1`

**Environment**
- TYPO3 version(s): 9.5.0
- news version: 7.0.6
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Mint 18.3, Nginx

**Possible Solution**
According to documentation https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Slug.html

eval should be set to `uniqueInPid`, then we don't need to play with [Routing Enhancers and Aspects](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html).

Tested and works.

Regards

**Edit**

Also you have eval twice:
``` php
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['path_segment']['config'] = [
        'type' => 'slug',
        'size' => 30, 'size' => 50,
        'eval' => 'nospace,alphanum_x,lower,unique',
        'generatorOptions' => [
            'fields' => ['title']
        ],
        'fallbackCharacter' => '-',
        // MY CHANGE
        'eval' => 'uniqueInPid',
        'default' => ''
    ];
```

**Comment by georgringer** [comment]
Thanks for your detailed report!
I am using `uniqueInSite` to avoid troubles if multiple sysfolders are used or for things like solr to create really unique slugs

**Comment by cosmox** [comment]
dont know if this issue reopen by comment, hope so because: i guess now it isnt possible to have the same path_segment in different languages!

Test it on 8.7.20 on two different instances with news 7.0.8

**Example**
First title: /somthing/with/it/
path_segment: ibm

Second title: /de/irgendwas/mit/it/
path_segment: ibm

Third title: fr/quelque/chose/avec/
path_segment: ibm

**Needed result**
/somthing/with/it/ibm
/de/irgendwas/mit/it/ibm
/fr/quelque/chose/avec/ibm

**Actual result**
when saving the path_segment is changed, so we get now:
/somthing/with/it/ibm
/de/irgendwas/mit/it/ibm0
fr/quelque/chose/avec/ibm1

maybe, ibm should be ibm in any languages :)

**Comment by georgringer** [comment]
Imo this is a core issue then

**Comment by hdnetmaxamann** [comment]
Hey @georgringer, i dont think this is a TYPO3 Core issue, its because of the TCA configuration:

`'path_segment' => [
            'exclude' => true,
            'label' => $ll . 'tx_news_domain_model_news.path_segment',
            'config' => [
                'type' => 'input',
                'size' => 30,
                'eval' => 'nospace,alphanum_x,lower,unique',
            ]
        ],`

because of eval 'unique'. 

This has to be somehow including the sys_language_uid in the table. Because its a common usecase that a news have a equal path_segment.
