### ISSUE TITLE
Dont work Speaking URL path segment

### ISSUE THREAD

**Issue by VladZadorozhnyy** [georgringer/news#777]
![typo3news](https://user-images.githubusercontent.com/24506959/47703245-da6b7980-dc49-11e8-8bcd-92be8dd3c7ab.PNG)
## Bug Report

**Current Behavior**
I wrote a clear URL, but it does not work out clear 
tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=13&cHash=cddefbcfb25b989cbbf4de8ffd2adcf5

**Expected behavior/output**
technologists

**Environment**
- TYPO3 version(s): [e.g. 9.5.0]
- news version: [e.g. 7.0.7]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [e.g.  Windows 10]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
Core issue

**Comment by OliverSchloebe** [comment]
Hi Georg,

sorry for bringing this issue back from the dead but hoping there're any news on providing speaking URIs out-of-the-box for `news`.

Since your last reply on this was on Oct 30th when TYPO3 9.5.x hasn't been out yet, here's me hoping speaking URIs for `news` will be available soon.

Seems like TYPOe 9.5.x introduced several new ways like `Routing Enhancers` (https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html#extbase-plugin-enhancer) or the TCA type `slug` which provides an `generatorOptions` array.

Any news on providing this out-of-the-box? Thanks a lot!
