### ISSUE TITLE
Wrong URL's in TYPO3 search

### ISSUE THREAD

**Issue by Liquado** [georgringer/news#862]
## Bug Report

**Current Behavior**
Using speaking URL's in TYPO3 9.5, indexed_search generates wrong URL's for News detail page results.

**Expected behavior/output**
Correct Links in indexed_search results ;-)

**Environment**
- TYPO3 version(s): 9.5.4
- news version: 7.0.8
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: FreeBSD 11.2-RELEASE-p8, PHP 7.2.15

[config.yaml.txt](https://github.com/georgringer/news/files/2899365/config.yaml.txt)

**Comment by georgringer** [comment]
not a core issue

**Comment by Tonyt8** [comment]
Hello,
Please forgive me for opening this closed thread. I do not know where else to ask for help/advise.
I am having the same problem as Liquado.  
I read your comments "bug", "invalid" and "wontfix".
Please can you tell me where I should look to fix the issue?
**Would you be prepared to help if payment for your services was arranged?**

When I add to the "site config.yaml" the routeEnhancers Newsplugin code the indexed search will not link to the news detail pages. I do get nice readable URL's. 
The indexed search will link when I only use the news hash addresses

I use:
 TYPO3 version(s): 9.5.4
 news version: 7.0.7

Regards,
Tony

**Comment by maechler** [comment]
@Liquado @Tonyt8 This may happen if the field `static_page_arguments` of the table `index_phash` is empty or missing the `action` and `controller` parameters. If everything is correct, it should look something like this:

```
{"tx_news_pi1":{"action":"detail","controller":"News","news":"1"}}
```

This happens most likely after you upgraded from TYPO3 8 to TYPO3 9, because this field only exists from TYPO3 9 on. I guess a solution could be to clear the `indexed_search` cache and reindex the news entries.

**Comment by Oktopuce** [comment]
What you also have to know is that `static_page_arguments` is not set if `routeEnhancers` is not configure for news because in that case, it's not **static arguments** but **dynamic arguments**.
